services:
  postgres:
    image: postgres:17-alpine
    container_name: alhiraa-db
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: alhiraa_atms
      POSTGRES_USER: alhiraa
      POSTGRES_PASSWORD: alhiraa_dev_2026
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: alhiraa-redis
    restart: unless-stopped
    ports:
      - '6379:6379'
    volumes:
      - redisdata:/data

volumes:
  pgdata:
  redisdata:
