import { PrismaClient } from '../src/generated/prisma';
import { PrismaPg } from '@prisma/adapter-pg';

const prisma = new PrismaClient({ adapter: new PrismaPg({ connectionString: process.env.DATABASE_URL || 'postgresql://alhiraa:alhiraa_dev_2026@localhost:5432/alhiraa_atms' }) });

const tradeNames: string[] = [
  'AC Technician Split & Window',
  'Accountant',
  'Aluminium Fabricator',
  'Animal Warden',
  'Any Helper',
  'Arabic Chef',
  'Area Restaurant Manager',
  'Asst. Electrician',
  'Asst. Cook',
  'Asst. Plumber',
  'Asst. Restaurant Manager',
  'Asst. Supervisor',
  'Asst. Waiter',
  'Auto AC Technician',
  'Auto Electrician',
  'Auto Mobile Engineer',
  'Auto Mobile Technician',
  'AutoCAD Operator',
  'CDP',
  'Chef',
  'D-CDP',
  'Bakery & Pastry Man',
  'Sous Chef',
  'Bakery Man',
  'Manager',
  'Banquet Supervisor',
  'Bartender',
  'Barber Female',
  'Barber Male',
  'Barista',
  'Bell Boy',
  'Bike Mechanic',
  'Boiler Operator',
  'Bouncer',
  'Bulldozer Operator',
  'Busser',
  'Butcher',
  'Butcher & Slaughterer',
  'Butcher Machine Cutter',
  'Cable Jointer',
  'Camp Boss',
  'Captain',
  'Cashier',
  'Catering Supervisor',
  'Chapati Maker',
  'Chartered Accountant',
  'Civil Engineer',
  'Civil Foreman',
  'Helper',
  'Civil Supervisor',
  'Cobbler',
  'Cold Kitchen Chef',
  'Computer Embroider',
  'Computer Engineer',
  'Computer Hardware & Networking',
  'Computer Operator',
  'Computer Technician',
  'Continental Chef',
  'Crane Operator',
  'Data Entry Operator',
  'Delivery Boy',
  'Denter',
  'Dialysis Machine Technician',
  'Mechanic',
  'Doctor',
  'Document Controller',
  'Draftsman Civil',
  'Draftsman Mechanical',
  'Draughtsman',
  'Duct Erector',
  'Duct Fabricator',
  'Duct Insulator',
  'Ductman',
  'Electrical Engineer',
  'Electrical Supervisor',
  'Electrician 220V',
  'Electrician 220V & 440V',
  'Electrician 440V',
  'Electrician Panel Board',
  'Electrical Technician',
  'Excavator Operator',
  'Executive Chef',
  'F&B Service',
  'F&B Supervisor',
  'Female Nurse',
  'Finishing Carpenter',
  'Gardener',
  'Welder',
  'Cook',
  'Gents Tailor',
  'Glass Designer',
  'Gold Smith',
  'Graphic Designer',
  'Gym Trainer',
  'Host',
  'Housekeeper',
  'Housekeeping Supervisor',
  'HR',
  'HR Manager',
  'HV Driver',
  'HVAC Chiller Plant Technician',
  'HVAC Foreman',
  'HVAC Technician',
  'IATA Officer',
  'Instrument Technician',
  'Interior Designer',
  'IT Engineer',
  'JCB Operator',
  'Juice Maker',
  'Kitchen Steward',
  'Ladies Tailor',
  'Land Surveyor',
  'Laptop Technician',
  'Laundry Boy',
  'Laundry Supervisor',
  'Lift Technician',
  'LMV Driver',
  'Loading & Unloading',
  'Logistics Manager',
  'Logistics Officer',
  'Logistics Supervisor',
  'Machine Embroider',
  'Male Nurse',
  'Mechanical Engineer',
  'Mechanical Supervisor',
  'Merchandiser',
  'Mobile Crane Operator',
  'Mobile Hardware Technician',
  'Mobile Software Technician',
  'Mocktail Maker',
  'Office Boy',
  'Office Machine Operator',
  'Packers',
  'Paratha Maker',
  'Pest Control',
  'LMV Mechanic Petrol',
  'LMV Mechanic Diesel',
  'HV Mechanic Petrol',
  'HV Mechanic Diesel',
  'Pharmacist',
  'Photographer',
  'Pipe Fitter',
  'Pizza Maker',
  'Plumber',
  'Poclain Operator',
  'POP Worker',
  'Quraan Hafez',
  'RCC Fitter',
  'Receptionist',
  'Refrigeration Technician',
  'Restaurant Manager',
  'Restaurant Shift Manager',
  'Restaurant Supervisor',
  'Rigger',
  'Room Boy',
  'Runner',
  'Safety Engineer',
  'Safety Officer',
  'Salad Maker',
  'Sales Manager',
  'Scaffolder',
  'Screen Printer',
  'Security Guard',
  'Senior Waiter',
  'Service Crew',
  'Service Quality Controller',
  'Food Quality Controller',
  'Shuttering Carpenter',
  'Sofa Maker',
  'Software Developer',
  'Spray Painter',
  'Steel Fabricator',
  'Steel Fixer',
  'Steward',
  'Potter',
  'Storekeeper',
  'Teacher',
  'Tele Caller',
  'Mason',
  'Timekeeper',
  'Tower Crane Operator',
  'Driver',
  'Tyre Technician',
  'Utility Operator',
  'Waiter',
  'Wall Painter',
  'Warehouse Manager',
  'Warehouse Supervisor',
  'Web Developer',
  'Xray Technician',
];

async function main() {
  let count = 0;

  for (let i = 0; i < tradeNames.length; i++) {
    const name = tradeNames[i];
    await prisma.trade.upsert({
      where: { name },
      update: {},
      create: {
        name,
        display_order: i + 1,
      },
    });
    count++;
  }

  console.log(`Upserted ${count} trades successfully.`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
